# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: write
permissions:
  contents: write
on:
 push:
    branches:
      - dev
 schedule:
     -
      cron: "0 0 * * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: run_send
      env:
        ddsecret: ${{ secrets.DDSECRET }}
        ddtoken: ${{ secrets.DDTOKEN }}
        secret: ${{ secrets.SERVERSECRET }}
      run: |
        python dayliySentence.py
    - name: clone
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: /
        branch: main
        force: false
        token: ${{ secrets.ACCESS_TOKEN }}